name = "EarthEngine"
uuid = "e0774970-6faf-4e9a-8c34-3860fa82b5ca"
authors = ["kmarkert <kel.markert@gmail.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "^ 1.0"
PyCall = "^ 1.90.0"

