name = "EarthEngine"
uuid = "e0774970-6faf-4e9a-8c34-3860fa82b5ca"
authors = ["kmarkert <kel.markert@gmail.com>"]
version = "0.3.1"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
OrderedCollections = "^1.4.0"
PyCall = "^1.90.0"
julia = "^1.0"
